version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
    - target: 80 
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  flaks-app:
    container_name: flask-app
    image: trio-flask-app:latest
    build: ./flask-app
  db:
    container_name: trio-db
    image: trio-db:latest
    build: ./db